#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr recode
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom glue glue
#' @importFrom memoise memoise
#' @importFrom readr read_csv
#' @importFrom rlang .data
#' @importFrom rlang abort
#' @importFrom rlang exec
#' @importFrom stringr str_pad
#' @importFrom tibble tibble
#' @importFrom tidyr nest
#' @importFrom tidyselect all_of
#' @importFrom tiltIndicator emissions_profile
#' @importFrom tiltIndicator emissions_profile_upstream
#' @importFrom tiltIndicator sector_profile
#' @importFrom tiltIndicator sector_profile_any_polish_output_at_company_level
#' @importFrom tiltIndicator sector_profile_upstream
#' @importFrom tiltIndicator unnest_company
#' @importFrom tiltIndicator unnest_product
#' @importFrom tiltToyData toy_emissions_profile_any_companies
#' @importFrom tiltToyData toy_emissions_profile_products
#' @importFrom tiltToyData toy_emissions_profile_upstream_products
#' @importFrom tiltToyData toy_sector_profile_any_scenarios
#' @importFrom tiltToyData toy_sector_profile_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_products
#' @importFrom utils hasName
#' @importFrom utils str
#' @importFrom withr local_options
## usethis namespace: end
NULL
